sudo: required
language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: publish
      name: "OSX packaging"
      if: branch = master
      os: osx
      script: 
        - npm install
        - npm run package-mac
        - ls
        - ls release-builds

    - stage: publish
      name: "Linux packaging"
      if: branch = master
      os: linux
      script: 
        - npm install
        - npm run package-linux
        - ls
        - ls release-builds
